version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo
      - mvn -v

  pre_build:
    commands:
      - echo

  build:
    commands:
      - echo
      - mvn clean package -DskipTests

  post_build:
    commands:
      - echo

artifacts:
  files:
    - 'target/*.jar'
  discard-paths: yes